version: '3.8'

services:
  backend:
    build: #builds the docker image locally
      context: ./spring-server
      dockerfile: Dockerfile.test
    # env_file:
    #   - ./spring-server/src/main/resources/.env
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL_TEST}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME_TEST}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      REDIS_HOST: redisTest #container
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      TMDB_API_KEY: ${TMDB_API_KEY}
  
      

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}

  redisTest:
    image: redis
    ports:
      - "6379:6379"

