version: '3.8'

services:

  backend:
    build: #builds the docker image locally else
      context: ./spring-server
      dockerfile: Dockerfile
    image: aj09/movie-server
    env_file:
      - ./spring-server/src/main/resources/.env 
    ports:
      - 3000:3000
    environment: # overrides variables .env in ./
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      TMDB_API_KEY: ${TMDB_API_KEY}

