version: '3.8'

services:
  backend:
    build:
      context: ./spring-server
      dockerfile: Dockerfile
    image: aj09/movie-server
    env_file:
      - ./spring-server/src/main/resources/.env
    ports:
      - 3000:3000
    depends_on:
      - database
      - redisContainer
    environment:
      REDIS_HOST: redisContainer
      REDIS_PORT: 6379

  frontend:
    build: 
      context: ./react-client
      dockerfile: Dockerfile
    image: aj09/movie-client
    ports:
      - '80:80'
    depends_on:
      - backend

  database:
    image: postgres
    restart: always
    env_file:
      - ./spring-server/src/main/resources/.env
    volumes:
      - ./data:/var/lib/postgresql/data

  redisContainer:
    image: redis
    ports:
      - "6379:6379"
