spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver #spring dependency
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache: 
    redis:
      # time-to-live: 3600000 #1 hr
      time-to-live: 10000
  jackson: # convert Java objects to JSON with snake case to be consistent with frontend
    property-naming-strategy: SNAKE_CASE
server.port: 3000